name: dagger

# Include Traefik to start both Traefik and Dagger engine with one command
# include:
#   - ../../_nuvola/traefik-mkcert-docker/compose.yaml

services:
  dagger_engine:
    profiles:
      - dagger
      - full
    image: ${DAGGER_ENGINE_IMAGE}
    container_name: ${DAGGER_ENGINE_NAME}
    network_mode: host
    privileged: true
    restart: always
    volumes:
      # - /var/lib/dagger:/var/lib/dagger
      - dagger_engine_data:/var/lib/dagger
      # Add the volume below to have the engine use the custom mkcert CA
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.pem
    environment:
      # - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      # - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      # - _EXPERIMENTAL_DAGGER_RUNNER_HOST=unix:///var/run/buildkit/buildkitd.sock
      ####     Load from direnv (.envrc)
      - PATH=${DAGGER_PATH}
      - _EXPERIMENTAL_DAGGER_RUNNER_HOST=${DAGGER_EXPERIMENTAL_DAGGER_RUNNER_HOST}
      # ⚠️ The following environment variables are used to specify the SDKs to be used by the engine ⚠️
      # ⚠️ Update the values below to the latest SDK versions every time you update the Dagger engine version ⚠️
      # - DAGGER_GO_SDK_MANIFEST_DIGEST=sha256:0bbceb0c4f1c346d3408087273bce50bd6ffaa39d76d783b4c177421a984c5f0
      # - DAGGER_PYTHON_SDK_MANIFEST_DIGEST=sha256:c64096425c63f26e2e301643eb3a25f4e533881a8b49d87c2a596a2405c923eb
      # - DAGGER_TYPESCRIPT_SDK_MANIFEST_DIGEST=sha256:c0aa2496d90869c1c73451bd70780c572a29a849a7e96fbd334d840e405572ba
      ####     Load from direnv (.envrc)
      - DAGGER_GO_SDK_MANIFEST_DIGEST=${DAGGER_GO_SDK_MANIFEST_DIGEST}
      - DAGGER_PYTHON_SDK_MANIFEST_DIGEST=${DAGGER_PYTHON_SDK_MANIFEST_DIGEST}
      - DAGGER_TYPESCRIPT_SDK_MANIFEST_DIGEST=${DAGGER_TYPESCRIPT_SDK_MANIFEST_DIGEST}
    command: dagger-entrypoint.sh --debug

volumes:
  dagger_engine_data:
    # driver: local
    # driver_opts:
    #   type: tmpfs
    #   device: tmpfs
    #   o: size=1G,uid=1000,gid=1000
