name: dagger

include:
  - ../../_nuvola/traefik-mkcert-docker/compose.yaml

services:

  dagger_engine:
    profiles:
      - dagger
      - full
    image: ${DAGGER_ENGINE_IMAGE}
    container_name: ${DAGGER_ENGINE_CUSTOM}
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - /var/lib/dagger:/var/lib/dagger
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.pem
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - DAGGER_GO_SDK_MANIFEST_DIGEST=sha256:4421bf2cfd1def7fba1fb677c54e35dab63cf59f70df32bd04eb1738b1c90c17
      - DAGGER_PYTHON_SDK_MANIFEST_DIGEST=sha256:c5c56696d7df8abb56f8de0998dc70026c75a2943fc06f8a41091ebc68f387ef
      - DAGGER_TYPESCRIPT_SDK_MANIFEST_DIGEST=sha256:7a02b582988ce4c66940e234198e8409b89827b3115bc504e8056b1577b00d83
      - _EXPERIMENTAL_DAGGER_RUNNER_HOST=unix:///var/run/buildkit/buildkitd.sock
    # command: --debug
