name: dagger

# Include Traefik to start both Traefik and Dagger engine with one command
# include:
#   - ../../_nuvola/traefik-mkcert-docker/compose.yaml

services:
  dagger_engine:
    profiles:
      - dagger
      - full
    image: ${DAGGER_ENGINE_IMAGE}
    container_name: ${DAGGER_ENGINE_NAME}
    network_mode: host
    privileged: true
    restart: always
    volumes:
      # - /var/lib/dagger:/var/lib/dagger
      - dagger_engine_data:/var/lib/dagger
      # Add the volume below to have the engine use the custom mkcert CA
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.pem
    environment:
      # - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - _EXPERIMENTAL_DAGGER_RUNNER_HOST=unix:///var/run/buildkit/buildkitd.sock
      # ⚠️ The following environment variables are used to specify the SDKs to be used by the engine ⚠️
      # ⚠️ Update the values below to the latest SDK versions every time you update the Dagger engine version ⚠️
      - DAGGER_GO_SDK_MANIFEST_DIGEST=sha256:392b15870818b172e8af5ab372632aa43de4192a1baba26d2fc8dc3f03e3a60a
      - DAGGER_PYTHON_SDK_MANIFEST_DIGEST=sha256:dab793f796ad1734fb92209d826563c51a36258652acdb8f3647ea33cf8a83e7
      - DAGGER_TYPESCRIPT_SDK_MANIFEST_DIGEST=sha256:6e4bf41e2a2388012bf63e859eec2f0e4f0a30a14337d139e092213ce39deeb2

    command: dagger-entrypoint.sh --debug

volumes:
  dagger_engine_data:
    # driver: local
    # driver_opts:
    #   type: tmpfs
    #   device: tmpfs
    #   o: size=1G,uid=1000,gid=1000
